@startdot
digraph graph01 {
node [color=Red]
       1->{2 3}
       2->{4 5}
       3->{6 7}
       4->{8}
       5->{8}
       6->{9}
       7->{9}
       8->{10}
       9->{11}
       10-> {12}
       11->{12}


}


@enddot