# Project information
site_name: Data Science Project
site_url: https://github.com/fralfaro/python_project
site_author: Francisco Alfaro
site_description:

# Repository
repo_name: fralfaro/python_project
repo_url: https://github.com/fralfaro/python_project
edit_uri: ''

# Markdown extensions
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tasklist
  - pymdownx.tabbed
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

# Extra javascript
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Theme
theme:
  name: material
  language: es
  logo: images/book.svg
  favicon: images/python.svg
  features:
    - navigation.instant
    - navigation.top
    - navigation.footer
    - content.code.annotate
    - search.suggest
    - search.highlight
  palette:
    # Light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/fralfaro
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.com/fralfaro
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/faam/
    - icon: fontawesome/brands/kaggle
      link: https://www.kaggle.com/faamds
    - icon: fontawesome/brands/medium
      link: https://medium.com/@fralfaro
    - icon: fontawesome/solid/globe
      link: https://fralfaro.github.io/portfolio/

# Plugins
plugins:
  - mkdocs-jupyter:
      kernel_name: python3
  - search

# TOC
nav:
    - Home: index.md
    - Sobre el repositorio:
      - general/intro.md
      - general/tips.md
      - Carpetas y Archivos:
          - general/src.md
          - general/tests.md
          - general/models.md
          - general/data.md
          - general/pipeline.md
          - general/docs.md
    - Sobre el proyecto:
      - project/intro.md
      - project/tips.md
      - project/description.md
      - project/working.md
      - Principales Resultados:
          - Resultado 01: project/result_01.ipynb
          - Resultado 02: project/result_02.ipynb
          - Resultado 03: project/result_03.ipynb
    - to_do.md
